name: App Deploy To Github Pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
    env:
      REACT_APP_MOCK_SERVER_URL: ${{secrets.REACT_APP_MOCK_SERVER_URL}}
    
    
    
      
